fit:
  model:
    class_path: src.models.nets.CNN_LSTM_Net
    init_args:
      input_size: 1
      cnn_out_channels: 64
      kernel_size: 3
      lstm_hidden_size: 64
      lstm_num_layers: 1
      lr: 1e-3
      output_size: 1
      normalizer:
        class_path: src.utils.normalizer.MaxMinNormalizer
  data:
    input_path: data/processed/spot.csv
    input_column: Close
    window_size: 7
    batch_size: 64
    predict_size: 1
  trainer:
    logger:
      init_args:
        experiment_name: Close
        run_name: CNN_LSTM