fit:
  model:
    class_path: src.models.nets.FractalNet
    init_args:
      input_size: 64
      output_size: 1
      n_columns: 1
      init_channels: 64
      p_ldrop: 0.15
      dropout_probs:
        - 0.0
      gdrop_ratio: 0.
      gap: 0
      init: xavier
      pad_type: zero
      doubling: False
      consist_gdrop: False
      dropout_pos: CDBR
      lr: 1e-3
      normalizer:
        class_path: src.utils.normalizer.MaxMinNormalizer
  data:
    input_path: data/processed/spot.csv
    input_column: Close
    window_size: 7
    batch_size: 64
    predict_size: 1
  trainer:
    logger:
      init_args:
        experiment_name: Close
        run_name: FractalNet