fit:
  model:
    class_path: src.models.nets.CNN_LSTM_Net
    init_args:
      input_size: 1
      cnn_out_channels: 128
      kernel_size: 3
      lstm_hidden_size: 128
      lstm_num_layers: 2
      lr: 1e-3
      output_size: 32
      normalizer:
        class_path: src.utils.normalizer.MaxMinNormalizer
  data:
    input_path: data/processed/global_active_power_v2.csv
    input_column: Global_active_power
    window_size: 64
    batch_size: 64
    predict_size: 32
  trainer:
    logger:
      init_args:
        experiment_name: Global_active_power
        run_name: CNN_LSTM