model:
  class: FractalNet
  constant_parameters:
    data_shape:
      - 1
      - 30
      - 1
    pad_type: zero
    doubling: False
    consist_gdrop: True
    gap: 0
    dropout_pos: CDBR
trainer:
  max_epochs: 800
  early_stopping_patience: 50
hyperparameters:
  dropout_probs:
    type: categorical
    choices:
      - [0., 0.1]
      - [0., 0.1, 0.2]
      - [0., 0.1, 0.2, 0.3]
  n_columns:
    type: int
    range:
      low: 2
      high: 5
  init_channels:
    type: categorical
    choices:
      - 8
      - 16
      - 32
      - 64
  p_ldrop:
    type: categorical
    choices:
      - 0.1
      - 0.2
      - 0.3
  gdrop_ratio:
    type: categorical
    choices:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
  init:
    type: categorical
    choices:
      - xavier
      - torch
optuna:
  n_trials: 30
  timeout: 1800
