model:
  class_path: src.models.nets.LSTM_Net
  init_args:
    input_size: 1
    hidden_size: 100
    num_layers: 1
    bidirectional: False
    lr: 1e-3
data:
  input_path: data/processed/global_active_power.csv
  input_column: Global_active_power_MinMaxScaler
  window_size: 100
trainer:
  logger:
    init_args:
      experiment_name: Global_active_power_MinMaxScaler
      run_name: LSTM