fit:
  model:
    class_path: src.models.nets.LSTM_Net
    init_args:
      input_size: 1
      hidden_size: 64
      num_layers: 1
      bidirectional: True
      lr: 1e-3
      output_size: 1
      normalizer:
        class_path: src.utils.normalizer.MaxMinNormalizer
  data:
    input_path: data/processed/global_active_power_v2.csv
    input_column: Global_active_power
    window_size: 7
    batch_size: 64
    predict_size: 1
  trainer:
    logger:
      init_args:
        experiment_name: Global_active_power
        run_name: BiLSTM