fit:
  model:
    class_path: src.models.nets.CNN_LSTM_Net
    init_args:
      input_size: 1
      cnn_out_channels: 128
      kernel_size: 6
      lstm_hidden_size: 128
      lstm_num_layers: 1
      lr: 1e-3
      output_size: 16
      normalizer:
        class_path: src.utils.normalizer.MaxMinNormalizer
  data:
    input_path: data/processed/sunspots_v2.csv
    input_column: "Monthly Mean Total Sunspot Number"
    window_size: 64
    batch_size: 64
    predict_size: 16
  trainer:
    logger:
      init_args:
        experiment_name: "Monthly Mean Total Sunspot Number"
        run_name: CNN_LSTM