model:
  class_path: src.models.nets.CNN_LSTM_Net
  init_args:
    input_size: 1
    cnn_out_channels: 64
    kernel_size: 4
    lstm_hidden_size: 100
    lstm_num_layers: 1
    fc_output_size: 1
    lr: 1e-3
data:
  input_path: data/processed/Sunspots.csv
  input_column: Monthly Mean Total Sunspot Number
  window_size: 132
  batch_size: 512
trainer:
  logger:
    init_args:
      experiment_name: Sunspots
      run_name: CNN_LSTM