model:
  class_path: src.models.nets.LSTM_Net
  init_args:
    input_size: 1
    hidden_size: 100
    num_layers: 1
    bidirectional: False
    lr: 1e-3
data:
  input_path: data/processed/Sunspots.csv
  input_column: Monthly Mean Total Sunspot Number
  window_size: 132
  batch_size: 512
trainer:
  logger:
    init_args:
      experiment_name: Sunspots
      run_name: LSTM