fit:
  model:
    class_path: src.models.nets.LSTM_Net
    init_args:
      input_size: 1
      hidden_size: 256
      num_layers: 2
      bidirectional: True
      lr: 1e-3
      output_size: 32
      normalizer:
        class_path: src.utils.normalizer.MaxMinNormalizer
  data:
    input_path: data/processed/sunspots_v2.csv
    input_column: Monthly Mean Total Sunspot Number
    window_size: 128
    predict_size: 32
    batch_size: 64
  trainer:
    logger:
      init_args:
        experiment_name: "Monthly Mean Total Sunspot Number"
        run_name: BiLSTM